// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYlCe017Q0gtuRq36gOlkJbzj5_PWFR4I',
    appId: '1:945664194801:web:531267e232c114c30f5150',
    messagingSenderId: '945664194801',
    projectId: 'fire-firstapp',
    authDomain: 'fire-firstapp.firebaseapp.com',
    storageBucket: 'fire-firstapp.appspot.com',
    measurementId: 'G-NDKD6H74PH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoWeYMKczrXUSDenGtuMtFkMHZepCDJIE',
    appId: '1:945664194801:android:1fdbaf4f6732ca9c0f5150',
    messagingSenderId: '945664194801',
    projectId: 'fire-firstapp',
    storageBucket: 'fire-firstapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4S0GP0c-PhO4QgSQsq0cNKv3krjL_jVM',
    appId: '1:945664194801:ios:97ea3f3fbd2a16260f5150',
    messagingSenderId: '945664194801',
    projectId: 'fire-firstapp',
    storageBucket: 'fire-firstapp.appspot.com',
    iosBundleId: 'com.myfirstapp.firstapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4S0GP0c-PhO4QgSQsq0cNKv3krjL_jVM',
    appId: '1:945664194801:ios:97ea3f3fbd2a16260f5150',
    messagingSenderId: '945664194801',
    projectId: 'fire-firstapp',
    storageBucket: 'fire-firstapp.appspot.com',
    iosBundleId: 'com.myfirstapp.firstapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYlCe017Q0gtuRq36gOlkJbzj5_PWFR4I',
    appId: '1:945664194801:web:235c420773bf61c50f5150',
    messagingSenderId: '945664194801',
    projectId: 'fire-firstapp',
    authDomain: 'fire-firstapp.firebaseapp.com',
    storageBucket: 'fire-firstapp.appspot.com',
    measurementId: 'G-87GHDMZSLF',
  );
}
